version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./property-management-system
    restart: always
    ports:
      - "8081:8081"  # Changed to match your local port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # JWT Config
      APPLICATION_SECURITY_JWT_SECRET_KEY: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxp
      APPLICATION_SECURITY_JWT_EXPIRATION: 86400000
      APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION: 604800000
      # Email Config
      # SPRING_MAIL_HOST: smtp.gmail.com
      # SPRING_MAIL_PORT: 587
      # SPRING_MAIL_USERNAME: jesseirungu3@gmail.com
      # SPRING_MAIL_PASSWORD: 
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: true
    depends_on:
      - db

  frontend:
    build: ./property-management-system-ui
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db-data: